/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class farkas_tdk_firstndk_Load */

#ifndef _Included_farkas_tdk_firstndk_Load
#define _Included_farkas_tdk_firstndk_Load
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     farkas_tdk_firstndk_Load
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_farkas_tdk_firstndk_Load_addInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     farkas_tdk_firstndk_Load
 * Method:    reduceInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_farkas_tdk_firstndk_Load_reduceInt
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
